/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the CreateLinkTokenRequestTeller type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLinkTokenRequestTeller{}

// CreateLinkTokenRequestTeller An object specifying information about the Teller configuration to use when creating a link token. 
type CreateLinkTokenRequestTeller struct {
	Config *CreateLinkTokenRequestTellerConfig `json:"config,omitempty"`
}

// NewCreateLinkTokenRequestTeller instantiates a new CreateLinkTokenRequestTeller object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkTokenRequestTeller() *CreateLinkTokenRequestTeller {
	this := CreateLinkTokenRequestTeller{}
	return &this
}

// NewCreateLinkTokenRequestTellerWithDefaults instantiates a new CreateLinkTokenRequestTeller object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkTokenRequestTellerWithDefaults() *CreateLinkTokenRequestTeller {
	this := CreateLinkTokenRequestTeller{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *CreateLinkTokenRequestTeller) GetConfig() CreateLinkTokenRequestTellerConfig {
	if o == nil || IsNil(o.Config) {
		var ret CreateLinkTokenRequestTellerConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkTokenRequestTeller) GetConfigOk() (*CreateLinkTokenRequestTellerConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateLinkTokenRequestTeller) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given CreateLinkTokenRequestTellerConfig and assigns it to the Config field.
func (o *CreateLinkTokenRequestTeller) SetConfig(v CreateLinkTokenRequestTellerConfig) {
	o.Config = &v
}

func (o CreateLinkTokenRequestTeller) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLinkTokenRequestTeller) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableCreateLinkTokenRequestTeller struct {
	value *CreateLinkTokenRequestTeller
	isSet bool
}

func (v NullableCreateLinkTokenRequestTeller) Get() *CreateLinkTokenRequestTeller {
	return v.value
}

func (v *NullableCreateLinkTokenRequestTeller) Set(val *CreateLinkTokenRequestTeller) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkTokenRequestTeller) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkTokenRequestTeller) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkTokenRequestTeller(val *CreateLinkTokenRequestTeller) *NullableCreateLinkTokenRequestTeller {
	return &NullableCreateLinkTokenRequestTeller{value: val, isSet: true}
}

func (v NullableCreateLinkTokenRequestTeller) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkTokenRequestTeller) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


