/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the CreateEntityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEntityRequest{}

// CreateEntityRequest struct for CreateEntityRequest
type CreateEntityRequest struct {
	// Id of the entity
	Id *string `json:"id,omitempty"`
	// Email of the entity
	Email *string `json:"email,omitempty"`
	// These will force the user to connect through all of these aggregators
	Aggregators []Aggregator `json:"aggregators,omitempty"`
	InstitutionIds []string `json:"institution_ids,omitempty"`
}

// NewCreateEntityRequest instantiates a new CreateEntityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEntityRequest() *CreateEntityRequest {
	this := CreateEntityRequest{}
	return &this
}

// NewCreateEntityRequestWithDefaults instantiates a new CreateEntityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEntityRequestWithDefaults() *CreateEntityRequest {
	this := CreateEntityRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateEntityRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateEntityRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateEntityRequest) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateEntityRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateEntityRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateEntityRequest) SetEmail(v string) {
	o.Email = &v
}

// GetAggregators returns the Aggregators field value if set, zero value otherwise.
func (o *CreateEntityRequest) GetAggregators() []Aggregator {
	if o == nil || IsNil(o.Aggregators) {
		var ret []Aggregator
		return ret
	}
	return o.Aggregators
}

// GetAggregatorsOk returns a tuple with the Aggregators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityRequest) GetAggregatorsOk() ([]Aggregator, bool) {
	if o == nil || IsNil(o.Aggregators) {
		return nil, false
	}
	return o.Aggregators, true
}

// HasAggregators returns a boolean if a field has been set.
func (o *CreateEntityRequest) HasAggregators() bool {
	if o != nil && !IsNil(o.Aggregators) {
		return true
	}

	return false
}

// SetAggregators gets a reference to the given []Aggregator and assigns it to the Aggregators field.
func (o *CreateEntityRequest) SetAggregators(v []Aggregator) {
	o.Aggregators = v
}

// GetInstitutionIds returns the InstitutionIds field value if set, zero value otherwise.
func (o *CreateEntityRequest) GetInstitutionIds() []string {
	if o == nil || IsNil(o.InstitutionIds) {
		var ret []string
		return ret
	}
	return o.InstitutionIds
}

// GetInstitutionIdsOk returns a tuple with the InstitutionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEntityRequest) GetInstitutionIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.InstitutionIds) {
		return nil, false
	}
	return o.InstitutionIds, true
}

// HasInstitutionIds returns a boolean if a field has been set.
func (o *CreateEntityRequest) HasInstitutionIds() bool {
	if o != nil && !IsNil(o.InstitutionIds) {
		return true
	}

	return false
}

// SetInstitutionIds gets a reference to the given []string and assigns it to the InstitutionIds field.
func (o *CreateEntityRequest) SetInstitutionIds(v []string) {
	o.InstitutionIds = v
}

func (o CreateEntityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEntityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Aggregators) {
		toSerialize["aggregators"] = o.Aggregators
	}
	if !IsNil(o.InstitutionIds) {
		toSerialize["institution_ids"] = o.InstitutionIds
	}
	return toSerialize, nil
}

type NullableCreateEntityRequest struct {
	value *CreateEntityRequest
	isSet bool
}

func (v NullableCreateEntityRequest) Get() *CreateEntityRequest {
	return v.value
}

func (v *NullableCreateEntityRequest) Set(val *CreateEntityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEntityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEntityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEntityRequest(val *CreateEntityRequest) *NullableCreateEntityRequest {
	return &NullableCreateEntityRequest{value: val, isSet: true}
}

func (v NullableCreateEntityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEntityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


