/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetFinancialConnectionsBalanceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinancialConnectionsBalanceRequest{}

// GetFinancialConnectionsBalanceRequest struct for GetFinancialConnectionsBalanceRequest
type GetFinancialConnectionsBalanceRequest struct {
	// Access token for authentication
	AccessToken string `json:"access_token"`
	Options *GetFinancialConnectionsBalanceRequestOptions `json:"options,omitempty"`
}

type _GetFinancialConnectionsBalanceRequest GetFinancialConnectionsBalanceRequest

// NewGetFinancialConnectionsBalanceRequest instantiates a new GetFinancialConnectionsBalanceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinancialConnectionsBalanceRequest(accessToken string) *GetFinancialConnectionsBalanceRequest {
	this := GetFinancialConnectionsBalanceRequest{}
	this.AccessToken = accessToken
	return &this
}

// NewGetFinancialConnectionsBalanceRequestWithDefaults instantiates a new GetFinancialConnectionsBalanceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinancialConnectionsBalanceRequestWithDefaults() *GetFinancialConnectionsBalanceRequest {
	this := GetFinancialConnectionsBalanceRequest{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *GetFinancialConnectionsBalanceRequest) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsBalanceRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *GetFinancialConnectionsBalanceRequest) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *GetFinancialConnectionsBalanceRequest) GetOptions() GetFinancialConnectionsBalanceRequestOptions {
	if o == nil || IsNil(o.Options) {
		var ret GetFinancialConnectionsBalanceRequestOptions
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsBalanceRequest) GetOptionsOk() (*GetFinancialConnectionsBalanceRequestOptions, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *GetFinancialConnectionsBalanceRequest) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given GetFinancialConnectionsBalanceRequestOptions and assigns it to the Options field.
func (o *GetFinancialConnectionsBalanceRequest) SetOptions(v GetFinancialConnectionsBalanceRequestOptions) {
	o.Options = &v
}

func (o GetFinancialConnectionsBalanceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinancialConnectionsBalanceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

func (o *GetFinancialConnectionsBalanceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFinancialConnectionsBalanceRequest := _GetFinancialConnectionsBalanceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFinancialConnectionsBalanceRequest)

	if err != nil {
		return err
	}

	*o = GetFinancialConnectionsBalanceRequest(varGetFinancialConnectionsBalanceRequest)

	return err
}

type NullableGetFinancialConnectionsBalanceRequest struct {
	value *GetFinancialConnectionsBalanceRequest
	isSet bool
}

func (v NullableGetFinancialConnectionsBalanceRequest) Get() *GetFinancialConnectionsBalanceRequest {
	return v.value
}

func (v *NullableGetFinancialConnectionsBalanceRequest) Set(val *GetFinancialConnectionsBalanceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinancialConnectionsBalanceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinancialConnectionsBalanceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinancialConnectionsBalanceRequest(val *GetFinancialConnectionsBalanceRequest) *NullableGetFinancialConnectionsBalanceRequest {
	return &NullableGetFinancialConnectionsBalanceRequest{value: val, isSet: true}
}

func (v NullableGetFinancialConnectionsBalanceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinancialConnectionsBalanceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


