/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the FinancialConnectionDetailsMx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialConnectionDetailsMx{}

// FinancialConnectionDetailsMx Data needed to query data from MX
type FinancialConnectionDetailsMx struct {
	// User GUID for MX
	UserGuid string `json:"user_guid"`
	// Member GUID for MX
	MemberGuid string `json:"member_guid"`
}

// NewFinancialConnectionDetailsMx instantiates a new FinancialConnectionDetailsMx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialConnectionDetailsMx(userGuid string, memberGuid string) *FinancialConnectionDetailsMx {
	this := FinancialConnectionDetailsMx{}
	this.UserGuid = userGuid
	this.MemberGuid = memberGuid
	return &this
}

// NewFinancialConnectionDetailsMxWithDefaults instantiates a new FinancialConnectionDetailsMx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialConnectionDetailsMxWithDefaults() *FinancialConnectionDetailsMx {
	this := FinancialConnectionDetailsMx{}
	return &this
}

// GetUserGuid returns the UserGuid field value
func (o *FinancialConnectionDetailsMx) GetUserGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserGuid
}

// GetUserGuidOk returns a tuple with the UserGuid field value
// and a boolean to check if the value has been set.
func (o *FinancialConnectionDetailsMx) GetUserGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserGuid, true
}

// SetUserGuid sets field value
func (o *FinancialConnectionDetailsMx) SetUserGuid(v string) {
	o.UserGuid = v
}

// GetMemberGuid returns the MemberGuid field value
func (o *FinancialConnectionDetailsMx) GetMemberGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemberGuid
}

// GetMemberGuidOk returns a tuple with the MemberGuid field value
// and a boolean to check if the value has been set.
func (o *FinancialConnectionDetailsMx) GetMemberGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberGuid, true
}

// SetMemberGuid sets field value
func (o *FinancialConnectionDetailsMx) SetMemberGuid(v string) {
	o.MemberGuid = v
}

func (o FinancialConnectionDetailsMx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialConnectionDetailsMx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_guid"] = o.UserGuid
	toSerialize["member_guid"] = o.MemberGuid
	return toSerialize, nil
}

type NullableFinancialConnectionDetailsMx struct {
	value *FinancialConnectionDetailsMx
	isSet bool
}

func (v NullableFinancialConnectionDetailsMx) Get() *FinancialConnectionDetailsMx {
	return v.value
}

func (v *NullableFinancialConnectionDetailsMx) Set(val *FinancialConnectionDetailsMx) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialConnectionDetailsMx) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialConnectionDetailsMx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialConnectionDetailsMx(val *FinancialConnectionDetailsMx) *NullableFinancialConnectionDetailsMx {
	return &NullableFinancialConnectionDetailsMx{value: val, isSet: true}
}

func (v NullableFinancialConnectionDetailsMx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialConnectionDetailsMx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


