/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the GetFinancialConnectionsAccountDetailsRequestOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinancialConnectionsAccountDetailsRequestOptions{}

// GetFinancialConnectionsAccountDetailsRequestOptions struct for GetFinancialConnectionsAccountDetailsRequestOptions
type GetFinancialConnectionsAccountDetailsRequestOptions struct {
	// An array of remote account ids to retrieve account details for.
	RemoteAccountIds []string `json:"remote_account_ids,omitempty"`
}

// NewGetFinancialConnectionsAccountDetailsRequestOptions instantiates a new GetFinancialConnectionsAccountDetailsRequestOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinancialConnectionsAccountDetailsRequestOptions() *GetFinancialConnectionsAccountDetailsRequestOptions {
	this := GetFinancialConnectionsAccountDetailsRequestOptions{}
	return &this
}

// NewGetFinancialConnectionsAccountDetailsRequestOptionsWithDefaults instantiates a new GetFinancialConnectionsAccountDetailsRequestOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinancialConnectionsAccountDetailsRequestOptionsWithDefaults() *GetFinancialConnectionsAccountDetailsRequestOptions {
	this := GetFinancialConnectionsAccountDetailsRequestOptions{}
	return &this
}

// GetRemoteAccountIds returns the RemoteAccountIds field value if set, zero value otherwise.
func (o *GetFinancialConnectionsAccountDetailsRequestOptions) GetRemoteAccountIds() []string {
	if o == nil || IsNil(o.RemoteAccountIds) {
		var ret []string
		return ret
	}
	return o.RemoteAccountIds
}

// GetRemoteAccountIdsOk returns a tuple with the RemoteAccountIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsAccountDetailsRequestOptions) GetRemoteAccountIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.RemoteAccountIds) {
		return nil, false
	}
	return o.RemoteAccountIds, true
}

// HasRemoteAccountIds returns a boolean if a field has been set.
func (o *GetFinancialConnectionsAccountDetailsRequestOptions) HasRemoteAccountIds() bool {
	if o != nil && !IsNil(o.RemoteAccountIds) {
		return true
	}

	return false
}

// SetRemoteAccountIds gets a reference to the given []string and assigns it to the RemoteAccountIds field.
func (o *GetFinancialConnectionsAccountDetailsRequestOptions) SetRemoteAccountIds(v []string) {
	o.RemoteAccountIds = v
}

func (o GetFinancialConnectionsAccountDetailsRequestOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinancialConnectionsAccountDetailsRequestOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RemoteAccountIds) {
		toSerialize["remote_account_ids"] = o.RemoteAccountIds
	}
	return toSerialize, nil
}

type NullableGetFinancialConnectionsAccountDetailsRequestOptions struct {
	value *GetFinancialConnectionsAccountDetailsRequestOptions
	isSet bool
}

func (v NullableGetFinancialConnectionsAccountDetailsRequestOptions) Get() *GetFinancialConnectionsAccountDetailsRequestOptions {
	return v.value
}

func (v *NullableGetFinancialConnectionsAccountDetailsRequestOptions) Set(val *GetFinancialConnectionsAccountDetailsRequestOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinancialConnectionsAccountDetailsRequestOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinancialConnectionsAccountDetailsRequestOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinancialConnectionsAccountDetailsRequestOptions(val *GetFinancialConnectionsAccountDetailsRequestOptions) *NullableGetFinancialConnectionsAccountDetailsRequestOptions {
	return &NullableGetFinancialConnectionsAccountDetailsRequestOptions{value: val, isSet: true}
}

func (v NullableGetFinancialConnectionsAccountDetailsRequestOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinancialConnectionsAccountDetailsRequestOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


