/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the FinancialConnectionsAccountCachedBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialConnectionsAccountCachedBalance{}

// FinancialConnectionsAccountCachedBalance struct for FinancialConnectionsAccountCachedBalance
type FinancialConnectionsAccountCachedBalance struct {
	// The amount of funds available, in cents, to be withdrawn from the account, as determined by the financial institution. The format of this value is a double. Available balance may be cached and is not guaranteed to be up-to-date in realtime unless the value was returned by /financial_connections/balances. For accounts with credit features, the available funds generally equal the credit limit. Some institutions may not provide an available balance calculation. If this is the case, Fuse will return a null value for the available balance. To ensure you have the most accurate information, we recommend obtaining the current balance by using 'balance.available || balance.current'.
	Available NullableFloat32 `json:"available,omitempty"`
	// Amount without factoring in pending balances, in cents. The format of this value is a double.
	Current NullableFloat32 `json:"current,omitempty"`
	// The ISO-4217 currency code of the balance.
	IsoCurrencyCode NullableString `json:"iso_currency_code,omitempty"`
	// The date of the last update to the balance.
	LastUpdatedDate NullableString `json:"last_updated_date,omitempty"`
}

// NewFinancialConnectionsAccountCachedBalance instantiates a new FinancialConnectionsAccountCachedBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialConnectionsAccountCachedBalance() *FinancialConnectionsAccountCachedBalance {
	this := FinancialConnectionsAccountCachedBalance{}
	return &this
}

// NewFinancialConnectionsAccountCachedBalanceWithDefaults instantiates a new FinancialConnectionsAccountCachedBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialConnectionsAccountCachedBalanceWithDefaults() *FinancialConnectionsAccountCachedBalance {
	this := FinancialConnectionsAccountCachedBalance{}
	return &this
}

// GetAvailable returns the Available field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FinancialConnectionsAccountCachedBalance) GetAvailable() float32 {
	if o == nil || IsNil(o.Available.Get()) {
		var ret float32
		return ret
	}
	return *o.Available.Get()
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FinancialConnectionsAccountCachedBalance) GetAvailableOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Available.Get(), o.Available.IsSet()
}

// HasAvailable returns a boolean if a field has been set.
func (o *FinancialConnectionsAccountCachedBalance) HasAvailable() bool {
	if o != nil && o.Available.IsSet() {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given NullableFloat32 and assigns it to the Available field.
func (o *FinancialConnectionsAccountCachedBalance) SetAvailable(v float32) {
	o.Available.Set(&v)
}
// SetAvailableNil sets the value for Available to be an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) SetAvailableNil() {
	o.Available.Set(nil)
}

// UnsetAvailable ensures that no value is present for Available, not even an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) UnsetAvailable() {
	o.Available.Unset()
}

// GetCurrent returns the Current field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FinancialConnectionsAccountCachedBalance) GetCurrent() float32 {
	if o == nil || IsNil(o.Current.Get()) {
		var ret float32
		return ret
	}
	return *o.Current.Get()
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FinancialConnectionsAccountCachedBalance) GetCurrentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Current.Get(), o.Current.IsSet()
}

// HasCurrent returns a boolean if a field has been set.
func (o *FinancialConnectionsAccountCachedBalance) HasCurrent() bool {
	if o != nil && o.Current.IsSet() {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given NullableFloat32 and assigns it to the Current field.
func (o *FinancialConnectionsAccountCachedBalance) SetCurrent(v float32) {
	o.Current.Set(&v)
}
// SetCurrentNil sets the value for Current to be an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) SetCurrentNil() {
	o.Current.Set(nil)
}

// UnsetCurrent ensures that no value is present for Current, not even an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) UnsetCurrent() {
	o.Current.Unset()
}

// GetIsoCurrencyCode returns the IsoCurrencyCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FinancialConnectionsAccountCachedBalance) GetIsoCurrencyCode() string {
	if o == nil || IsNil(o.IsoCurrencyCode.Get()) {
		var ret string
		return ret
	}
	return *o.IsoCurrencyCode.Get()
}

// GetIsoCurrencyCodeOk returns a tuple with the IsoCurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FinancialConnectionsAccountCachedBalance) GetIsoCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsoCurrencyCode.Get(), o.IsoCurrencyCode.IsSet()
}

// HasIsoCurrencyCode returns a boolean if a field has been set.
func (o *FinancialConnectionsAccountCachedBalance) HasIsoCurrencyCode() bool {
	if o != nil && o.IsoCurrencyCode.IsSet() {
		return true
	}

	return false
}

// SetIsoCurrencyCode gets a reference to the given NullableString and assigns it to the IsoCurrencyCode field.
func (o *FinancialConnectionsAccountCachedBalance) SetIsoCurrencyCode(v string) {
	o.IsoCurrencyCode.Set(&v)
}
// SetIsoCurrencyCodeNil sets the value for IsoCurrencyCode to be an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) SetIsoCurrencyCodeNil() {
	o.IsoCurrencyCode.Set(nil)
}

// UnsetIsoCurrencyCode ensures that no value is present for IsoCurrencyCode, not even an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) UnsetIsoCurrencyCode() {
	o.IsoCurrencyCode.Unset()
}

// GetLastUpdatedDate returns the LastUpdatedDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FinancialConnectionsAccountCachedBalance) GetLastUpdatedDate() string {
	if o == nil || IsNil(o.LastUpdatedDate.Get()) {
		var ret string
		return ret
	}
	return *o.LastUpdatedDate.Get()
}

// GetLastUpdatedDateOk returns a tuple with the LastUpdatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FinancialConnectionsAccountCachedBalance) GetLastUpdatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedDate.Get(), o.LastUpdatedDate.IsSet()
}

// HasLastUpdatedDate returns a boolean if a field has been set.
func (o *FinancialConnectionsAccountCachedBalance) HasLastUpdatedDate() bool {
	if o != nil && o.LastUpdatedDate.IsSet() {
		return true
	}

	return false
}

// SetLastUpdatedDate gets a reference to the given NullableString and assigns it to the LastUpdatedDate field.
func (o *FinancialConnectionsAccountCachedBalance) SetLastUpdatedDate(v string) {
	o.LastUpdatedDate.Set(&v)
}
// SetLastUpdatedDateNil sets the value for LastUpdatedDate to be an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) SetLastUpdatedDateNil() {
	o.LastUpdatedDate.Set(nil)
}

// UnsetLastUpdatedDate ensures that no value is present for LastUpdatedDate, not even an explicit nil
func (o *FinancialConnectionsAccountCachedBalance) UnsetLastUpdatedDate() {
	o.LastUpdatedDate.Unset()
}

func (o FinancialConnectionsAccountCachedBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialConnectionsAccountCachedBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Available.IsSet() {
		toSerialize["available"] = o.Available.Get()
	}
	if o.Current.IsSet() {
		toSerialize["current"] = o.Current.Get()
	}
	if o.IsoCurrencyCode.IsSet() {
		toSerialize["iso_currency_code"] = o.IsoCurrencyCode.Get()
	}
	if o.LastUpdatedDate.IsSet() {
		toSerialize["last_updated_date"] = o.LastUpdatedDate.Get()
	}
	return toSerialize, nil
}

type NullableFinancialConnectionsAccountCachedBalance struct {
	value *FinancialConnectionsAccountCachedBalance
	isSet bool
}

func (v NullableFinancialConnectionsAccountCachedBalance) Get() *FinancialConnectionsAccountCachedBalance {
	return v.value
}

func (v *NullableFinancialConnectionsAccountCachedBalance) Set(val *FinancialConnectionsAccountCachedBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialConnectionsAccountCachedBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialConnectionsAccountCachedBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialConnectionsAccountCachedBalance(val *FinancialConnectionsAccountCachedBalance) *NullableFinancialConnectionsAccountCachedBalance {
	return &NullableFinancialConnectionsAccountCachedBalance{value: val, isSet: true}
}

func (v NullableFinancialConnectionsAccountCachedBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialConnectionsAccountCachedBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


