/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the TransactionCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionCategory{}

// TransactionCategory struct for TransactionCategory
type TransactionCategory struct {
	Primary TransactionCategoryPrimary `json:"primary"`
	Detailed TransactionCategoryDetailed `json:"detailed"`
}

// NewTransactionCategory instantiates a new TransactionCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionCategory(primary TransactionCategoryPrimary, detailed TransactionCategoryDetailed) *TransactionCategory {
	this := TransactionCategory{}
	this.Primary = primary
	this.Detailed = detailed
	return &this
}

// NewTransactionCategoryWithDefaults instantiates a new TransactionCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionCategoryWithDefaults() *TransactionCategory {
	this := TransactionCategory{}
	return &this
}

// GetPrimary returns the Primary field value
func (o *TransactionCategory) GetPrimary() TransactionCategoryPrimary {
	if o == nil {
		var ret TransactionCategoryPrimary
		return ret
	}

	return o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value
// and a boolean to check if the value has been set.
func (o *TransactionCategory) GetPrimaryOk() (*TransactionCategoryPrimary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Primary, true
}

// SetPrimary sets field value
func (o *TransactionCategory) SetPrimary(v TransactionCategoryPrimary) {
	o.Primary = v
}

// GetDetailed returns the Detailed field value
func (o *TransactionCategory) GetDetailed() TransactionCategoryDetailed {
	if o == nil {
		var ret TransactionCategoryDetailed
		return ret
	}

	return o.Detailed
}

// GetDetailedOk returns a tuple with the Detailed field value
// and a boolean to check if the value has been set.
func (o *TransactionCategory) GetDetailedOk() (*TransactionCategoryDetailed, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detailed, true
}

// SetDetailed sets field value
func (o *TransactionCategory) SetDetailed(v TransactionCategoryDetailed) {
	o.Detailed = v
}

func (o TransactionCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["primary"] = o.Primary
	toSerialize["detailed"] = o.Detailed
	return toSerialize, nil
}

type NullableTransactionCategory struct {
	value *TransactionCategory
	isSet bool
}

func (v NullableTransactionCategory) Get() *TransactionCategory {
	return v.value
}

func (v *NullableTransactionCategory) Set(val *TransactionCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionCategory(val *TransactionCategory) *NullableTransactionCategory {
	return &NullableTransactionCategory{value: val, isSet: true}
}

func (v NullableTransactionCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


