/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the CreateLinkTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLinkTokenResponse{}

// CreateLinkTokenResponse struct for CreateLinkTokenResponse
type CreateLinkTokenResponse struct {
	// Token needed by the frontend sdk to initiate the connection
	LinkToken string `json:"link_token"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

// NewCreateLinkTokenResponse instantiates a new CreateLinkTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkTokenResponse(linkToken string, requestId string) *CreateLinkTokenResponse {
	this := CreateLinkTokenResponse{}
	this.LinkToken = linkToken
	this.RequestId = requestId
	return &this
}

// NewCreateLinkTokenResponseWithDefaults instantiates a new CreateLinkTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkTokenResponseWithDefaults() *CreateLinkTokenResponse {
	this := CreateLinkTokenResponse{}
	return &this
}

// GetLinkToken returns the LinkToken field value
func (o *CreateLinkTokenResponse) GetLinkToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LinkToken
}

// GetLinkTokenOk returns a tuple with the LinkToken field value
// and a boolean to check if the value has been set.
func (o *CreateLinkTokenResponse) GetLinkTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkToken, true
}

// SetLinkToken sets field value
func (o *CreateLinkTokenResponse) SetLinkToken(v string) {
	o.LinkToken = v
}

// GetRequestId returns the RequestId field value
func (o *CreateLinkTokenResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *CreateLinkTokenResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *CreateLinkTokenResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o CreateLinkTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLinkTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["link_token"] = o.LinkToken
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

type NullableCreateLinkTokenResponse struct {
	value *CreateLinkTokenResponse
	isSet bool
}

func (v NullableCreateLinkTokenResponse) Get() *CreateLinkTokenResponse {
	return v.value
}

func (v *NullableCreateLinkTokenResponse) Set(val *CreateLinkTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkTokenResponse(val *CreateLinkTokenResponse) *NullableCreateLinkTokenResponse {
	return &NullableCreateLinkTokenResponse{value: val, isSet: true}
}

func (v NullableCreateLinkTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


