/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the CreateConsumerRiskReportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateConsumerRiskReportRequest{}

// CreateConsumerRiskReportRequest struct for CreateConsumerRiskReportRequest
type CreateConsumerRiskReportRequest struct {
	// A unique ID representing the bank account that this risk report is calculated for. Typically this will be a bank connection account ID from your application. It is currently used as a means of connecting events to the consumer risk report.
	AccountId string `json:"account_id"`
	// The ISO-4217 currency code of the transaction
	IsoCurrencyCode string `json:"iso_currency_code"`
	// The name of the end user associated with this consumer risk report.
	EndUserName *string `json:"end_user_name,omitempty"`
	// This is used to determine the timeframe and other metadata for the consumer risk report.
	CustomizationId string `json:"customization_id"`
}

// NewCreateConsumerRiskReportRequest instantiates a new CreateConsumerRiskReportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConsumerRiskReportRequest(accountId string, isoCurrencyCode string, customizationId string) *CreateConsumerRiskReportRequest {
	this := CreateConsumerRiskReportRequest{}
	this.AccountId = accountId
	this.IsoCurrencyCode = isoCurrencyCode
	this.CustomizationId = customizationId
	return &this
}

// NewCreateConsumerRiskReportRequestWithDefaults instantiates a new CreateConsumerRiskReportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConsumerRiskReportRequestWithDefaults() *CreateConsumerRiskReportRequest {
	this := CreateConsumerRiskReportRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CreateConsumerRiskReportRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CreateConsumerRiskReportRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CreateConsumerRiskReportRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetIsoCurrencyCode returns the IsoCurrencyCode field value
func (o *CreateConsumerRiskReportRequest) GetIsoCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IsoCurrencyCode
}

// GetIsoCurrencyCodeOk returns a tuple with the IsoCurrencyCode field value
// and a boolean to check if the value has been set.
func (o *CreateConsumerRiskReportRequest) GetIsoCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsoCurrencyCode, true
}

// SetIsoCurrencyCode sets field value
func (o *CreateConsumerRiskReportRequest) SetIsoCurrencyCode(v string) {
	o.IsoCurrencyCode = v
}

// GetEndUserName returns the EndUserName field value if set, zero value otherwise.
func (o *CreateConsumerRiskReportRequest) GetEndUserName() string {
	if o == nil || IsNil(o.EndUserName) {
		var ret string
		return ret
	}
	return *o.EndUserName
}

// GetEndUserNameOk returns a tuple with the EndUserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConsumerRiskReportRequest) GetEndUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.EndUserName) {
		return nil, false
	}
	return o.EndUserName, true
}

// HasEndUserName returns a boolean if a field has been set.
func (o *CreateConsumerRiskReportRequest) HasEndUserName() bool {
	if o != nil && !IsNil(o.EndUserName) {
		return true
	}

	return false
}

// SetEndUserName gets a reference to the given string and assigns it to the EndUserName field.
func (o *CreateConsumerRiskReportRequest) SetEndUserName(v string) {
	o.EndUserName = &v
}

// GetCustomizationId returns the CustomizationId field value
func (o *CreateConsumerRiskReportRequest) GetCustomizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomizationId
}

// GetCustomizationIdOk returns a tuple with the CustomizationId field value
// and a boolean to check if the value has been set.
func (o *CreateConsumerRiskReportRequest) GetCustomizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomizationId, true
}

// SetCustomizationId sets field value
func (o *CreateConsumerRiskReportRequest) SetCustomizationId(v string) {
	o.CustomizationId = v
}

func (o CreateConsumerRiskReportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateConsumerRiskReportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["iso_currency_code"] = o.IsoCurrencyCode
	if !IsNil(o.EndUserName) {
		toSerialize["end_user_name"] = o.EndUserName
	}
	toSerialize["customization_id"] = o.CustomizationId
	return toSerialize, nil
}

type NullableCreateConsumerRiskReportRequest struct {
	value *CreateConsumerRiskReportRequest
	isSet bool
}

func (v NullableCreateConsumerRiskReportRequest) Get() *CreateConsumerRiskReportRequest {
	return v.value
}

func (v *NullableCreateConsumerRiskReportRequest) Set(val *CreateConsumerRiskReportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConsumerRiskReportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConsumerRiskReportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConsumerRiskReportRequest(val *CreateConsumerRiskReportRequest) *NullableCreateConsumerRiskReportRequest {
	return &NullableCreateConsumerRiskReportRequest{value: val, isSet: true}
}

func (v NullableCreateConsumerRiskReportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConsumerRiskReportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


