/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetFinancialConnectionsOwnersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinancialConnectionsOwnersResponse{}

// GetFinancialConnectionsOwnersResponse struct for GetFinancialConnectionsOwnersResponse
type GetFinancialConnectionsOwnersResponse struct {
	Accounts []GetFinancialConnectionsOwnersResponseAccountsInner `json:"accounts"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

type _GetFinancialConnectionsOwnersResponse GetFinancialConnectionsOwnersResponse

// NewGetFinancialConnectionsOwnersResponse instantiates a new GetFinancialConnectionsOwnersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinancialConnectionsOwnersResponse(accounts []GetFinancialConnectionsOwnersResponseAccountsInner, requestId string) *GetFinancialConnectionsOwnersResponse {
	this := GetFinancialConnectionsOwnersResponse{}
	this.Accounts = accounts
	this.RequestId = requestId
	return &this
}

// NewGetFinancialConnectionsOwnersResponseWithDefaults instantiates a new GetFinancialConnectionsOwnersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinancialConnectionsOwnersResponseWithDefaults() *GetFinancialConnectionsOwnersResponse {
	this := GetFinancialConnectionsOwnersResponse{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *GetFinancialConnectionsOwnersResponse) GetAccounts() []GetFinancialConnectionsOwnersResponseAccountsInner {
	if o == nil {
		var ret []GetFinancialConnectionsOwnersResponseAccountsInner
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsOwnersResponse) GetAccountsOk() ([]GetFinancialConnectionsOwnersResponseAccountsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *GetFinancialConnectionsOwnersResponse) SetAccounts(v []GetFinancialConnectionsOwnersResponseAccountsInner) {
	o.Accounts = v
}

// GetRequestId returns the RequestId field value
func (o *GetFinancialConnectionsOwnersResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsOwnersResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *GetFinancialConnectionsOwnersResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o GetFinancialConnectionsOwnersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinancialConnectionsOwnersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *GetFinancialConnectionsOwnersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accounts",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFinancialConnectionsOwnersResponse := _GetFinancialConnectionsOwnersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFinancialConnectionsOwnersResponse)

	if err != nil {
		return err
	}

	*o = GetFinancialConnectionsOwnersResponse(varGetFinancialConnectionsOwnersResponse)

	return err
}

type NullableGetFinancialConnectionsOwnersResponse struct {
	value *GetFinancialConnectionsOwnersResponse
	isSet bool
}

func (v NullableGetFinancialConnectionsOwnersResponse) Get() *GetFinancialConnectionsOwnersResponse {
	return v.value
}

func (v *NullableGetFinancialConnectionsOwnersResponse) Set(val *GetFinancialConnectionsOwnersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinancialConnectionsOwnersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinancialConnectionsOwnersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinancialConnectionsOwnersResponse(val *GetFinancialConnectionsOwnersResponse) *NullableGetFinancialConnectionsOwnersResponse {
	return &NullableGetFinancialConnectionsOwnersResponse{value: val, isSet: true}
}

func (v NullableGetFinancialConnectionsOwnersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinancialConnectionsOwnersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


