/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetFinancialConnectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinancialConnectionResponse{}

// GetFinancialConnectionResponse struct for GetFinancialConnectionResponse
type GetFinancialConnectionResponse struct {
	FinancialConnection FinancialConnectionDetails `json:"financial_connection"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

type _GetFinancialConnectionResponse GetFinancialConnectionResponse

// NewGetFinancialConnectionResponse instantiates a new GetFinancialConnectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinancialConnectionResponse(financialConnection FinancialConnectionDetails, requestId string) *GetFinancialConnectionResponse {
	this := GetFinancialConnectionResponse{}
	this.FinancialConnection = financialConnection
	this.RequestId = requestId
	return &this
}

// NewGetFinancialConnectionResponseWithDefaults instantiates a new GetFinancialConnectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinancialConnectionResponseWithDefaults() *GetFinancialConnectionResponse {
	this := GetFinancialConnectionResponse{}
	return &this
}

// GetFinancialConnection returns the FinancialConnection field value
func (o *GetFinancialConnectionResponse) GetFinancialConnection() FinancialConnectionDetails {
	if o == nil {
		var ret FinancialConnectionDetails
		return ret
	}

	return o.FinancialConnection
}

// GetFinancialConnectionOk returns a tuple with the FinancialConnection field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionResponse) GetFinancialConnectionOk() (*FinancialConnectionDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinancialConnection, true
}

// SetFinancialConnection sets field value
func (o *GetFinancialConnectionResponse) SetFinancialConnection(v FinancialConnectionDetails) {
	o.FinancialConnection = v
}

// GetRequestId returns the RequestId field value
func (o *GetFinancialConnectionResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *GetFinancialConnectionResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o GetFinancialConnectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinancialConnectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["financial_connection"] = o.FinancialConnection
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *GetFinancialConnectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"financial_connection",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFinancialConnectionResponse := _GetFinancialConnectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFinancialConnectionResponse)

	if err != nil {
		return err
	}

	*o = GetFinancialConnectionResponse(varGetFinancialConnectionResponse)

	return err
}

type NullableGetFinancialConnectionResponse struct {
	value *GetFinancialConnectionResponse
	isSet bool
}

func (v NullableGetFinancialConnectionResponse) Get() *GetFinancialConnectionResponse {
	return v.value
}

func (v *NullableGetFinancialConnectionResponse) Set(val *GetFinancialConnectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinancialConnectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinancialConnectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinancialConnectionResponse(val *GetFinancialConnectionResponse) *NullableGetFinancialConnectionResponse {
	return &NullableGetFinancialConnectionResponse{value: val, isSet: true}
}

func (v NullableGetFinancialConnectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinancialConnectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


