/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the CreateLinkTokenRequestSnaptradeConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLinkTokenRequestSnaptradeConfig{}

// CreateLinkTokenRequestSnaptradeConfig struct for CreateLinkTokenRequestSnaptradeConfig
type CreateLinkTokenRequestSnaptradeConfig struct {
	// SnapTrade connection type. Defaults to 'read'
	ConnectionType *string `json:"connectionType,omitempty"`
}

// NewCreateLinkTokenRequestSnaptradeConfig instantiates a new CreateLinkTokenRequestSnaptradeConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkTokenRequestSnaptradeConfig() *CreateLinkTokenRequestSnaptradeConfig {
	this := CreateLinkTokenRequestSnaptradeConfig{}
	var connectionType string = "read"
	this.ConnectionType = &connectionType
	return &this
}

// NewCreateLinkTokenRequestSnaptradeConfigWithDefaults instantiates a new CreateLinkTokenRequestSnaptradeConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkTokenRequestSnaptradeConfigWithDefaults() *CreateLinkTokenRequestSnaptradeConfig {
	this := CreateLinkTokenRequestSnaptradeConfig{}
	var connectionType string = "read"
	this.ConnectionType = &connectionType
	return &this
}

// GetConnectionType returns the ConnectionType field value if set, zero value otherwise.
func (o *CreateLinkTokenRequestSnaptradeConfig) GetConnectionType() string {
	if o == nil || IsNil(o.ConnectionType) {
		var ret string
		return ret
	}
	return *o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkTokenRequestSnaptradeConfig) GetConnectionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionType) {
		return nil, false
	}
	return o.ConnectionType, true
}

// HasConnectionType returns a boolean if a field has been set.
func (o *CreateLinkTokenRequestSnaptradeConfig) HasConnectionType() bool {
	if o != nil && !IsNil(o.ConnectionType) {
		return true
	}

	return false
}

// SetConnectionType gets a reference to the given string and assigns it to the ConnectionType field.
func (o *CreateLinkTokenRequestSnaptradeConfig) SetConnectionType(v string) {
	o.ConnectionType = &v
}

func (o CreateLinkTokenRequestSnaptradeConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLinkTokenRequestSnaptradeConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConnectionType) {
		toSerialize["connectionType"] = o.ConnectionType
	}
	return toSerialize, nil
}

type NullableCreateLinkTokenRequestSnaptradeConfig struct {
	value *CreateLinkTokenRequestSnaptradeConfig
	isSet bool
}

func (v NullableCreateLinkTokenRequestSnaptradeConfig) Get() *CreateLinkTokenRequestSnaptradeConfig {
	return v.value
}

func (v *NullableCreateLinkTokenRequestSnaptradeConfig) Set(val *CreateLinkTokenRequestSnaptradeConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkTokenRequestSnaptradeConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkTokenRequestSnaptradeConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkTokenRequestSnaptradeConfig(val *CreateLinkTokenRequestSnaptradeConfig) *NullableCreateLinkTokenRequestSnaptradeConfig {
	return &NullableCreateLinkTokenRequestSnaptradeConfig{value: val, isSet: true}
}

func (v NullableCreateLinkTokenRequestSnaptradeConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkTokenRequestSnaptradeConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


