/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRecommendedFinancialInstitutionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRecommendedFinancialInstitutionsRequest{}

// GetRecommendedFinancialInstitutionsRequest struct for GetRecommendedFinancialInstitutionsRequest
type GetRecommendedFinancialInstitutionsRequest struct {
	// The session client secret created.
	SessionClientSecret string `json:"session_client_secret"`
}

type _GetRecommendedFinancialInstitutionsRequest GetRecommendedFinancialInstitutionsRequest

// NewGetRecommendedFinancialInstitutionsRequest instantiates a new GetRecommendedFinancialInstitutionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRecommendedFinancialInstitutionsRequest(sessionClientSecret string) *GetRecommendedFinancialInstitutionsRequest {
	this := GetRecommendedFinancialInstitutionsRequest{}
	this.SessionClientSecret = sessionClientSecret
	return &this
}

// NewGetRecommendedFinancialInstitutionsRequestWithDefaults instantiates a new GetRecommendedFinancialInstitutionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRecommendedFinancialInstitutionsRequestWithDefaults() *GetRecommendedFinancialInstitutionsRequest {
	this := GetRecommendedFinancialInstitutionsRequest{}
	return &this
}

// GetSessionClientSecret returns the SessionClientSecret field value
func (o *GetRecommendedFinancialInstitutionsRequest) GetSessionClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionClientSecret
}

// GetSessionClientSecretOk returns a tuple with the SessionClientSecret field value
// and a boolean to check if the value has been set.
func (o *GetRecommendedFinancialInstitutionsRequest) GetSessionClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionClientSecret, true
}

// SetSessionClientSecret sets field value
func (o *GetRecommendedFinancialInstitutionsRequest) SetSessionClientSecret(v string) {
	o.SessionClientSecret = v
}

func (o GetRecommendedFinancialInstitutionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRecommendedFinancialInstitutionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_client_secret"] = o.SessionClientSecret
	return toSerialize, nil
}

func (o *GetRecommendedFinancialInstitutionsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRecommendedFinancialInstitutionsRequest := _GetRecommendedFinancialInstitutionsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRecommendedFinancialInstitutionsRequest)

	if err != nil {
		return err
	}

	*o = GetRecommendedFinancialInstitutionsRequest(varGetRecommendedFinancialInstitutionsRequest)

	return err
}

type NullableGetRecommendedFinancialInstitutionsRequest struct {
	value *GetRecommendedFinancialInstitutionsRequest
	isSet bool
}

func (v NullableGetRecommendedFinancialInstitutionsRequest) Get() *GetRecommendedFinancialInstitutionsRequest {
	return v.value
}

func (v *NullableGetRecommendedFinancialInstitutionsRequest) Set(val *GetRecommendedFinancialInstitutionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRecommendedFinancialInstitutionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRecommendedFinancialInstitutionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRecommendedFinancialInstitutionsRequest(val *GetRecommendedFinancialInstitutionsRequest) *NullableGetRecommendedFinancialInstitutionsRequest {
	return &NullableGetRecommendedFinancialInstitutionsRequest{value: val, isSet: true}
}

func (v NullableGetRecommendedFinancialInstitutionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRecommendedFinancialInstitutionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


