/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the GetFinancialConnectionsAccountsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinancialConnectionsAccountsRequest{}

// GetFinancialConnectionsAccountsRequest struct for GetFinancialConnectionsAccountsRequest
type GetFinancialConnectionsAccountsRequest struct {
	// Access token for authentication
	AccessToken string `json:"access_token"`
}

// NewGetFinancialConnectionsAccountsRequest instantiates a new GetFinancialConnectionsAccountsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinancialConnectionsAccountsRequest(accessToken string) *GetFinancialConnectionsAccountsRequest {
	this := GetFinancialConnectionsAccountsRequest{}
	this.AccessToken = accessToken
	return &this
}

// NewGetFinancialConnectionsAccountsRequestWithDefaults instantiates a new GetFinancialConnectionsAccountsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinancialConnectionsAccountsRequestWithDefaults() *GetFinancialConnectionsAccountsRequest {
	this := GetFinancialConnectionsAccountsRequest{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *GetFinancialConnectionsAccountsRequest) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsAccountsRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *GetFinancialConnectionsAccountsRequest) SetAccessToken(v string) {
	o.AccessToken = v
}

func (o GetFinancialConnectionsAccountsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinancialConnectionsAccountsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	return toSerialize, nil
}

type NullableGetFinancialConnectionsAccountsRequest struct {
	value *GetFinancialConnectionsAccountsRequest
	isSet bool
}

func (v NullableGetFinancialConnectionsAccountsRequest) Get() *GetFinancialConnectionsAccountsRequest {
	return v.value
}

func (v *NullableGetFinancialConnectionsAccountsRequest) Set(val *GetFinancialConnectionsAccountsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinancialConnectionsAccountsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinancialConnectionsAccountsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinancialConnectionsAccountsRequest(val *GetFinancialConnectionsAccountsRequest) *NullableGetFinancialConnectionsAccountsRequest {
	return &NullableGetFinancialConnectionsAccountsRequest{value: val, isSet: true}
}

func (v NullableGetFinancialConnectionsAccountsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinancialConnectionsAccountsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


