/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the GetInvestmentHoldingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInvestmentHoldingsResponse{}

// GetInvestmentHoldingsResponse struct for GetInvestmentHoldingsResponse
type GetInvestmentHoldingsResponse struct {
	Accounts []FinancialConnectionsAccount `json:"accounts"`
	Holdings []FinancialConnectionsHolding `json:"holdings"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

// NewGetInvestmentHoldingsResponse instantiates a new GetInvestmentHoldingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInvestmentHoldingsResponse(accounts []FinancialConnectionsAccount, holdings []FinancialConnectionsHolding, requestId string) *GetInvestmentHoldingsResponse {
	this := GetInvestmentHoldingsResponse{}
	this.Accounts = accounts
	this.Holdings = holdings
	this.RequestId = requestId
	return &this
}

// NewGetInvestmentHoldingsResponseWithDefaults instantiates a new GetInvestmentHoldingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInvestmentHoldingsResponseWithDefaults() *GetInvestmentHoldingsResponse {
	this := GetInvestmentHoldingsResponse{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *GetInvestmentHoldingsResponse) GetAccounts() []FinancialConnectionsAccount {
	if o == nil {
		var ret []FinancialConnectionsAccount
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *GetInvestmentHoldingsResponse) GetAccountsOk() ([]FinancialConnectionsAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *GetInvestmentHoldingsResponse) SetAccounts(v []FinancialConnectionsAccount) {
	o.Accounts = v
}

// GetHoldings returns the Holdings field value
func (o *GetInvestmentHoldingsResponse) GetHoldings() []FinancialConnectionsHolding {
	if o == nil {
		var ret []FinancialConnectionsHolding
		return ret
	}

	return o.Holdings
}

// GetHoldingsOk returns a tuple with the Holdings field value
// and a boolean to check if the value has been set.
func (o *GetInvestmentHoldingsResponse) GetHoldingsOk() ([]FinancialConnectionsHolding, bool) {
	if o == nil {
		return nil, false
	}
	return o.Holdings, true
}

// SetHoldings sets field value
func (o *GetInvestmentHoldingsResponse) SetHoldings(v []FinancialConnectionsHolding) {
	o.Holdings = v
}

// GetRequestId returns the RequestId field value
func (o *GetInvestmentHoldingsResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *GetInvestmentHoldingsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *GetInvestmentHoldingsResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o GetInvestmentHoldingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInvestmentHoldingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	toSerialize["holdings"] = o.Holdings
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

type NullableGetInvestmentHoldingsResponse struct {
	value *GetInvestmentHoldingsResponse
	isSet bool
}

func (v NullableGetInvestmentHoldingsResponse) Get() *GetInvestmentHoldingsResponse {
	return v.value
}

func (v *NullableGetInvestmentHoldingsResponse) Set(val *GetInvestmentHoldingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInvestmentHoldingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInvestmentHoldingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInvestmentHoldingsResponse(val *GetInvestmentHoldingsResponse) *NullableGetInvestmentHoldingsResponse {
	return &NullableGetInvestmentHoldingsResponse{value: val, isSet: true}
}

func (v NullableGetInvestmentHoldingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInvestmentHoldingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


