/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the CreateConsumerRiskReportResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateConsumerRiskReportResponse{}

// CreateConsumerRiskReportResponse struct for CreateConsumerRiskReportResponse
type CreateConsumerRiskReportResponse struct {
	Id string `json:"id"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

// NewCreateConsumerRiskReportResponse instantiates a new CreateConsumerRiskReportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConsumerRiskReportResponse(id string, requestId string) *CreateConsumerRiskReportResponse {
	this := CreateConsumerRiskReportResponse{}
	this.Id = id
	this.RequestId = requestId
	return &this
}

// NewCreateConsumerRiskReportResponseWithDefaults instantiates a new CreateConsumerRiskReportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConsumerRiskReportResponseWithDefaults() *CreateConsumerRiskReportResponse {
	this := CreateConsumerRiskReportResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateConsumerRiskReportResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateConsumerRiskReportResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateConsumerRiskReportResponse) SetId(v string) {
	o.Id = v
}

// GetRequestId returns the RequestId field value
func (o *CreateConsumerRiskReportResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *CreateConsumerRiskReportResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *CreateConsumerRiskReportResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o CreateConsumerRiskReportResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateConsumerRiskReportResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

type NullableCreateConsumerRiskReportResponse struct {
	value *CreateConsumerRiskReportResponse
	isSet bool
}

func (v NullableCreateConsumerRiskReportResponse) Get() *CreateConsumerRiskReportResponse {
	return v.value
}

func (v *NullableCreateConsumerRiskReportResponse) Set(val *CreateConsumerRiskReportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConsumerRiskReportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConsumerRiskReportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConsumerRiskReportResponse(val *CreateConsumerRiskReportResponse) *NullableCreateConsumerRiskReportResponse {
	return &NullableCreateConsumerRiskReportResponse{value: val, isSet: true}
}

func (v NullableCreateConsumerRiskReportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConsumerRiskReportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


