/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the AssetReportAccountsInnerBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetReportAccountsInnerBalance{}

// AssetReportAccountsInnerBalance struct for AssetReportAccountsInnerBalance
type AssetReportAccountsInnerBalance struct {
	// Amount after factoring in pending balances
	Available *float32 `json:"available,omitempty"`
	// Amount without factoring in pending balances
	Current *float32 `json:"current,omitempty"`
	// The ISO-4217 currency code of the balance.
	IsoCurrencyCode *string `json:"iso_currency_code,omitempty"`
}

// NewAssetReportAccountsInnerBalance instantiates a new AssetReportAccountsInnerBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetReportAccountsInnerBalance() *AssetReportAccountsInnerBalance {
	this := AssetReportAccountsInnerBalance{}
	return &this
}

// NewAssetReportAccountsInnerBalanceWithDefaults instantiates a new AssetReportAccountsInnerBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetReportAccountsInnerBalanceWithDefaults() *AssetReportAccountsInnerBalance {
	this := AssetReportAccountsInnerBalance{}
	return &this
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *AssetReportAccountsInnerBalance) GetAvailable() float32 {
	if o == nil || IsNil(o.Available) {
		var ret float32
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetReportAccountsInnerBalance) GetAvailableOk() (*float32, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *AssetReportAccountsInnerBalance) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given float32 and assigns it to the Available field.
func (o *AssetReportAccountsInnerBalance) SetAvailable(v float32) {
	o.Available = &v
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *AssetReportAccountsInnerBalance) GetCurrent() float32 {
	if o == nil || IsNil(o.Current) {
		var ret float32
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetReportAccountsInnerBalance) GetCurrentOk() (*float32, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *AssetReportAccountsInnerBalance) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given float32 and assigns it to the Current field.
func (o *AssetReportAccountsInnerBalance) SetCurrent(v float32) {
	o.Current = &v
}

// GetIsoCurrencyCode returns the IsoCurrencyCode field value if set, zero value otherwise.
func (o *AssetReportAccountsInnerBalance) GetIsoCurrencyCode() string {
	if o == nil || IsNil(o.IsoCurrencyCode) {
		var ret string
		return ret
	}
	return *o.IsoCurrencyCode
}

// GetIsoCurrencyCodeOk returns a tuple with the IsoCurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetReportAccountsInnerBalance) GetIsoCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.IsoCurrencyCode) {
		return nil, false
	}
	return o.IsoCurrencyCode, true
}

// HasIsoCurrencyCode returns a boolean if a field has been set.
func (o *AssetReportAccountsInnerBalance) HasIsoCurrencyCode() bool {
	if o != nil && !IsNil(o.IsoCurrencyCode) {
		return true
	}

	return false
}

// SetIsoCurrencyCode gets a reference to the given string and assigns it to the IsoCurrencyCode field.
func (o *AssetReportAccountsInnerBalance) SetIsoCurrencyCode(v string) {
	o.IsoCurrencyCode = &v
}

func (o AssetReportAccountsInnerBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetReportAccountsInnerBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	if !IsNil(o.IsoCurrencyCode) {
		toSerialize["iso_currency_code"] = o.IsoCurrencyCode
	}
	return toSerialize, nil
}

type NullableAssetReportAccountsInnerBalance struct {
	value *AssetReportAccountsInnerBalance
	isSet bool
}

func (v NullableAssetReportAccountsInnerBalance) Get() *AssetReportAccountsInnerBalance {
	return v.value
}

func (v *NullableAssetReportAccountsInnerBalance) Set(val *AssetReportAccountsInnerBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetReportAccountsInnerBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetReportAccountsInnerBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetReportAccountsInnerBalance(val *AssetReportAccountsInnerBalance) *NullableAssetReportAccountsInnerBalance {
	return &NullableAssetReportAccountsInnerBalance{value: val, isSet: true}
}

func (v NullableAssetReportAccountsInnerBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetReportAccountsInnerBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


