/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetFinancialConnectionsAccountStatementResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFinancialConnectionsAccountStatementResponse{}

// GetFinancialConnectionsAccountStatementResponse struct for GetFinancialConnectionsAccountStatementResponse
type GetFinancialConnectionsAccountStatementResponse struct {
	// PDF statement URL.
	StatementUrl string `json:"statement_url"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

type _GetFinancialConnectionsAccountStatementResponse GetFinancialConnectionsAccountStatementResponse

// NewGetFinancialConnectionsAccountStatementResponse instantiates a new GetFinancialConnectionsAccountStatementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFinancialConnectionsAccountStatementResponse(statementUrl string, requestId string) *GetFinancialConnectionsAccountStatementResponse {
	this := GetFinancialConnectionsAccountStatementResponse{}
	this.StatementUrl = statementUrl
	this.RequestId = requestId
	return &this
}

// NewGetFinancialConnectionsAccountStatementResponseWithDefaults instantiates a new GetFinancialConnectionsAccountStatementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFinancialConnectionsAccountStatementResponseWithDefaults() *GetFinancialConnectionsAccountStatementResponse {
	this := GetFinancialConnectionsAccountStatementResponse{}
	return &this
}

// GetStatementUrl returns the StatementUrl field value
func (o *GetFinancialConnectionsAccountStatementResponse) GetStatementUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatementUrl
}

// GetStatementUrlOk returns a tuple with the StatementUrl field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsAccountStatementResponse) GetStatementUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatementUrl, true
}

// SetStatementUrl sets field value
func (o *GetFinancialConnectionsAccountStatementResponse) SetStatementUrl(v string) {
	o.StatementUrl = v
}

// GetRequestId returns the RequestId field value
func (o *GetFinancialConnectionsAccountStatementResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *GetFinancialConnectionsAccountStatementResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *GetFinancialConnectionsAccountStatementResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o GetFinancialConnectionsAccountStatementResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFinancialConnectionsAccountStatementResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["statement_url"] = o.StatementUrl
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *GetFinancialConnectionsAccountStatementResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"statement_url",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFinancialConnectionsAccountStatementResponse := _GetFinancialConnectionsAccountStatementResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFinancialConnectionsAccountStatementResponse)

	if err != nil {
		return err
	}

	*o = GetFinancialConnectionsAccountStatementResponse(varGetFinancialConnectionsAccountStatementResponse)

	return err
}

type NullableGetFinancialConnectionsAccountStatementResponse struct {
	value *GetFinancialConnectionsAccountStatementResponse
	isSet bool
}

func (v NullableGetFinancialConnectionsAccountStatementResponse) Get() *GetFinancialConnectionsAccountStatementResponse {
	return v.value
}

func (v *NullableGetFinancialConnectionsAccountStatementResponse) Set(val *GetFinancialConnectionsAccountStatementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFinancialConnectionsAccountStatementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFinancialConnectionsAccountStatementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFinancialConnectionsAccountStatementResponse(val *GetFinancialConnectionsAccountStatementResponse) *NullableGetFinancialConnectionsAccountStatementResponse {
	return &NullableGetFinancialConnectionsAccountStatementResponse{value: val, isSet: true}
}

func (v NullableGetFinancialConnectionsAccountStatementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFinancialConnectionsAccountStatementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


