/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"fmt"
)

// CreateLinkTokenRequestTellerConfigAccountFilterDepository - struct for CreateLinkTokenRequestTellerConfigAccountFilterDepository
type CreateLinkTokenRequestTellerConfigAccountFilterDepository struct {
	CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf *CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf
	String *string
}

// CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOfAsCreateLinkTokenRequestTellerConfigAccountFilterDepository is a convenience function that returns CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf wrapped in CreateLinkTokenRequestTellerConfigAccountFilterDepository
func CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOfAsCreateLinkTokenRequestTellerConfigAccountFilterDepository(v *CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf) CreateLinkTokenRequestTellerConfigAccountFilterDepository {
	return CreateLinkTokenRequestTellerConfigAccountFilterDepository{
		CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf: v,
	}
}

// stringAsCreateLinkTokenRequestTellerConfigAccountFilterDepository is a convenience function that returns string wrapped in CreateLinkTokenRequestTellerConfigAccountFilterDepository
func StringAsCreateLinkTokenRequestTellerConfigAccountFilterDepository(v *string) CreateLinkTokenRequestTellerConfigAccountFilterDepository {
	return CreateLinkTokenRequestTellerConfigAccountFilterDepository{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateLinkTokenRequestTellerConfigAccountFilterDepository) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf)
	if err == nil {
		jsonCreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf, _ := json.Marshal(dst.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf)
		if string(jsonCreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf) == "{}" { // empty struct
			dst.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf = nil
		} else {
			match++
		}
	} else {
		dst.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateLinkTokenRequestTellerConfigAccountFilterDepository)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateLinkTokenRequestTellerConfigAccountFilterDepository)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateLinkTokenRequestTellerConfigAccountFilterDepository) MarshalJSON() ([]byte, error) {
	if src.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf != nil {
		return json.Marshal(&src.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateLinkTokenRequestTellerConfigAccountFilterDepository) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf != nil {
		return obj.CreateLinkTokenRequestTellerConfigAccountFilterDepositoryOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository struct {
	value *CreateLinkTokenRequestTellerConfigAccountFilterDepository
	isSet bool
}

func (v NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository) Get() *CreateLinkTokenRequestTellerConfigAccountFilterDepository {
	return v.value
}

func (v *NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository) Set(val *CreateLinkTokenRequestTellerConfigAccountFilterDepository) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkTokenRequestTellerConfigAccountFilterDepository(val *CreateLinkTokenRequestTellerConfigAccountFilterDepository) *NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository {
	return &NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository{value: val, isSet: true}
}

func (v NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkTokenRequestTellerConfigAccountFilterDepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


