/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the FinancialConnectionsAccountInstitution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialConnectionsAccountInstitution{}

// FinancialConnectionsAccountInstitution struct for FinancialConnectionsAccountInstitution
type FinancialConnectionsAccountInstitution struct {
	Name *string `json:"name,omitempty"`
}

// NewFinancialConnectionsAccountInstitution instantiates a new FinancialConnectionsAccountInstitution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialConnectionsAccountInstitution() *FinancialConnectionsAccountInstitution {
	this := FinancialConnectionsAccountInstitution{}
	return &this
}

// NewFinancialConnectionsAccountInstitutionWithDefaults instantiates a new FinancialConnectionsAccountInstitution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialConnectionsAccountInstitutionWithDefaults() *FinancialConnectionsAccountInstitution {
	this := FinancialConnectionsAccountInstitution{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FinancialConnectionsAccountInstitution) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinancialConnectionsAccountInstitution) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FinancialConnectionsAccountInstitution) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FinancialConnectionsAccountInstitution) SetName(v string) {
	o.Name = &v
}

func (o FinancialConnectionsAccountInstitution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialConnectionsAccountInstitution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableFinancialConnectionsAccountInstitution struct {
	value *FinancialConnectionsAccountInstitution
	isSet bool
}

func (v NullableFinancialConnectionsAccountInstitution) Get() *FinancialConnectionsAccountInstitution {
	return v.value
}

func (v *NullableFinancialConnectionsAccountInstitution) Set(val *FinancialConnectionsAccountInstitution) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialConnectionsAccountInstitution) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialConnectionsAccountInstitution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialConnectionsAccountInstitution(val *FinancialConnectionsAccountInstitution) *NullableFinancialConnectionsAccountInstitution {
	return &NullableFinancialConnectionsAccountInstitution{value: val, isSet: true}
}

func (v NullableFinancialConnectionsAccountInstitution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialConnectionsAccountInstitution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


