/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MigrateFinancialConnectionsAggregatorConnectionDataMx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MigrateFinancialConnectionsAggregatorConnectionDataMx{}

// MigrateFinancialConnectionsAggregatorConnectionDataMx Details of the MX connection to migrate into the unified Fuse API.
type MigrateFinancialConnectionsAggregatorConnectionDataMx struct {
	// The unique identifier (GUID) of the user within the MX platform.
	UserGuid string `json:"user_guid"`
	// The unique identifier (GUID) of the member (connection) associated with the user within the MX platform.
	MemberGuid *string `json:"member_guid,omitempty"`
}

type _MigrateFinancialConnectionsAggregatorConnectionDataMx MigrateFinancialConnectionsAggregatorConnectionDataMx

// NewMigrateFinancialConnectionsAggregatorConnectionDataMx instantiates a new MigrateFinancialConnectionsAggregatorConnectionDataMx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMigrateFinancialConnectionsAggregatorConnectionDataMx(userGuid string) *MigrateFinancialConnectionsAggregatorConnectionDataMx {
	this := MigrateFinancialConnectionsAggregatorConnectionDataMx{}
	this.UserGuid = userGuid
	return &this
}

// NewMigrateFinancialConnectionsAggregatorConnectionDataMxWithDefaults instantiates a new MigrateFinancialConnectionsAggregatorConnectionDataMx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMigrateFinancialConnectionsAggregatorConnectionDataMxWithDefaults() *MigrateFinancialConnectionsAggregatorConnectionDataMx {
	this := MigrateFinancialConnectionsAggregatorConnectionDataMx{}
	return &this
}

// GetUserGuid returns the UserGuid field value
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) GetUserGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserGuid
}

// GetUserGuidOk returns a tuple with the UserGuid field value
// and a boolean to check if the value has been set.
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) GetUserGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserGuid, true
}

// SetUserGuid sets field value
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) SetUserGuid(v string) {
	o.UserGuid = v
}

// GetMemberGuid returns the MemberGuid field value if set, zero value otherwise.
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) GetMemberGuid() string {
	if o == nil || IsNil(o.MemberGuid) {
		var ret string
		return ret
	}
	return *o.MemberGuid
}

// GetMemberGuidOk returns a tuple with the MemberGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) GetMemberGuidOk() (*string, bool) {
	if o == nil || IsNil(o.MemberGuid) {
		return nil, false
	}
	return o.MemberGuid, true
}

// HasMemberGuid returns a boolean if a field has been set.
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) HasMemberGuid() bool {
	if o != nil && !IsNil(o.MemberGuid) {
		return true
	}

	return false
}

// SetMemberGuid gets a reference to the given string and assigns it to the MemberGuid field.
func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) SetMemberGuid(v string) {
	o.MemberGuid = &v
}

func (o MigrateFinancialConnectionsAggregatorConnectionDataMx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MigrateFinancialConnectionsAggregatorConnectionDataMx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_guid"] = o.UserGuid
	if !IsNil(o.MemberGuid) {
		toSerialize["member_guid"] = o.MemberGuid
	}
	return toSerialize, nil
}

func (o *MigrateFinancialConnectionsAggregatorConnectionDataMx) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_guid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMigrateFinancialConnectionsAggregatorConnectionDataMx := _MigrateFinancialConnectionsAggregatorConnectionDataMx{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMigrateFinancialConnectionsAggregatorConnectionDataMx)

	if err != nil {
		return err
	}

	*o = MigrateFinancialConnectionsAggregatorConnectionDataMx(varMigrateFinancialConnectionsAggregatorConnectionDataMx)

	return err
}

type NullableMigrateFinancialConnectionsAggregatorConnectionDataMx struct {
	value *MigrateFinancialConnectionsAggregatorConnectionDataMx
	isSet bool
}

func (v NullableMigrateFinancialConnectionsAggregatorConnectionDataMx) Get() *MigrateFinancialConnectionsAggregatorConnectionDataMx {
	return v.value
}

func (v *NullableMigrateFinancialConnectionsAggregatorConnectionDataMx) Set(val *MigrateFinancialConnectionsAggregatorConnectionDataMx) {
	v.value = val
	v.isSet = true
}

func (v NullableMigrateFinancialConnectionsAggregatorConnectionDataMx) IsSet() bool {
	return v.isSet
}

func (v *NullableMigrateFinancialConnectionsAggregatorConnectionDataMx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMigrateFinancialConnectionsAggregatorConnectionDataMx(val *MigrateFinancialConnectionsAggregatorConnectionDataMx) *NullableMigrateFinancialConnectionsAggregatorConnectionDataMx {
	return &NullableMigrateFinancialConnectionsAggregatorConnectionDataMx{value: val, isSet: true}
}

func (v NullableMigrateFinancialConnectionsAggregatorConnectionDataMx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMigrateFinancialConnectionsAggregatorConnectionDataMx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


