/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FinancialConnectionDetailsFlinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinancialConnectionDetailsFlinks{}

// FinancialConnectionDetailsFlinks Data needed to query data from Flinks
type FinancialConnectionDetailsFlinks struct {
	// Login Id for Flinks
	LoginId string `json:"login_id"`
}

type _FinancialConnectionDetailsFlinks FinancialConnectionDetailsFlinks

// NewFinancialConnectionDetailsFlinks instantiates a new FinancialConnectionDetailsFlinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinancialConnectionDetailsFlinks(loginId string) *FinancialConnectionDetailsFlinks {
	this := FinancialConnectionDetailsFlinks{}
	this.LoginId = loginId
	return &this
}

// NewFinancialConnectionDetailsFlinksWithDefaults instantiates a new FinancialConnectionDetailsFlinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinancialConnectionDetailsFlinksWithDefaults() *FinancialConnectionDetailsFlinks {
	this := FinancialConnectionDetailsFlinks{}
	return &this
}

// GetLoginId returns the LoginId field value
func (o *FinancialConnectionDetailsFlinks) GetLoginId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LoginId
}

// GetLoginIdOk returns a tuple with the LoginId field value
// and a boolean to check if the value has been set.
func (o *FinancialConnectionDetailsFlinks) GetLoginIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoginId, true
}

// SetLoginId sets field value
func (o *FinancialConnectionDetailsFlinks) SetLoginId(v string) {
	o.LoginId = v
}

func (o FinancialConnectionDetailsFlinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinancialConnectionDetailsFlinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["login_id"] = o.LoginId
	return toSerialize, nil
}

func (o *FinancialConnectionDetailsFlinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"login_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFinancialConnectionDetailsFlinks := _FinancialConnectionDetailsFlinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFinancialConnectionDetailsFlinks)

	if err != nil {
		return err
	}

	*o = FinancialConnectionDetailsFlinks(varFinancialConnectionDetailsFlinks)

	return err
}

type NullableFinancialConnectionDetailsFlinks struct {
	value *FinancialConnectionDetailsFlinks
	isSet bool
}

func (v NullableFinancialConnectionDetailsFlinks) Get() *FinancialConnectionDetailsFlinks {
	return v.value
}

func (v *NullableFinancialConnectionDetailsFlinks) Set(val *FinancialConnectionDetailsFlinks) {
	v.value = val
	v.isSet = true
}

func (v NullableFinancialConnectionDetailsFlinks) IsSet() bool {
	return v.isSet
}

func (v *NullableFinancialConnectionDetailsFlinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinancialConnectionDetailsFlinks(val *FinancialConnectionDetailsFlinks) *NullableFinancialConnectionDetailsFlinks {
	return &NullableFinancialConnectionDetailsFlinks{value: val, isSet: true}
}

func (v NullableFinancialConnectionDetailsFlinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinancialConnectionDetailsFlinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


