/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
)

// checks if the SyncTransactionsResponseRemovedInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncTransactionsResponseRemovedInner{}

// SyncTransactionsResponseRemovedInner struct for SyncTransactionsResponseRemovedInner
type SyncTransactionsResponseRemovedInner struct {
	TransactionId *string `json:"transaction_id,omitempty"`
}

// NewSyncTransactionsResponseRemovedInner instantiates a new SyncTransactionsResponseRemovedInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncTransactionsResponseRemovedInner() *SyncTransactionsResponseRemovedInner {
	this := SyncTransactionsResponseRemovedInner{}
	return &this
}

// NewSyncTransactionsResponseRemovedInnerWithDefaults instantiates a new SyncTransactionsResponseRemovedInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncTransactionsResponseRemovedInnerWithDefaults() *SyncTransactionsResponseRemovedInner {
	this := SyncTransactionsResponseRemovedInner{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *SyncTransactionsResponseRemovedInner) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncTransactionsResponseRemovedInner) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *SyncTransactionsResponseRemovedInner) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *SyncTransactionsResponseRemovedInner) SetTransactionId(v string) {
	o.TransactionId = &v
}

func (o SyncTransactionsResponseRemovedInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncTransactionsResponseRemovedInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	return toSerialize, nil
}

type NullableSyncTransactionsResponseRemovedInner struct {
	value *SyncTransactionsResponseRemovedInner
	isSet bool
}

func (v NullableSyncTransactionsResponseRemovedInner) Get() *SyncTransactionsResponseRemovedInner {
	return v.value
}

func (v *NullableSyncTransactionsResponseRemovedInner) Set(val *SyncTransactionsResponseRemovedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncTransactionsResponseRemovedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncTransactionsResponseRemovedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncTransactionsResponseRemovedInner(val *SyncTransactionsResponseRemovedInner) *NullableSyncTransactionsResponseRemovedInner {
	return &NullableSyncTransactionsResponseRemovedInner{value: val, isSet: true}
}

func (v NullableSyncTransactionsResponseRemovedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncTransactionsResponseRemovedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


