/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExchangeFinancialConnectionsPublicTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExchangeFinancialConnectionsPublicTokenRequest{}

// ExchangeFinancialConnectionsPublicTokenRequest struct for ExchangeFinancialConnectionsPublicTokenRequest
type ExchangeFinancialConnectionsPublicTokenRequest struct {
	// The public token created after a user connects with their financial institution
	PublicToken string `json:"public_token"`
}

type _ExchangeFinancialConnectionsPublicTokenRequest ExchangeFinancialConnectionsPublicTokenRequest

// NewExchangeFinancialConnectionsPublicTokenRequest instantiates a new ExchangeFinancialConnectionsPublicTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchangeFinancialConnectionsPublicTokenRequest(publicToken string) *ExchangeFinancialConnectionsPublicTokenRequest {
	this := ExchangeFinancialConnectionsPublicTokenRequest{}
	this.PublicToken = publicToken
	return &this
}

// NewExchangeFinancialConnectionsPublicTokenRequestWithDefaults instantiates a new ExchangeFinancialConnectionsPublicTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchangeFinancialConnectionsPublicTokenRequestWithDefaults() *ExchangeFinancialConnectionsPublicTokenRequest {
	this := ExchangeFinancialConnectionsPublicTokenRequest{}
	return &this
}

// GetPublicToken returns the PublicToken field value
func (o *ExchangeFinancialConnectionsPublicTokenRequest) GetPublicToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicToken
}

// GetPublicTokenOk returns a tuple with the PublicToken field value
// and a boolean to check if the value has been set.
func (o *ExchangeFinancialConnectionsPublicTokenRequest) GetPublicTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicToken, true
}

// SetPublicToken sets field value
func (o *ExchangeFinancialConnectionsPublicTokenRequest) SetPublicToken(v string) {
	o.PublicToken = v
}

func (o ExchangeFinancialConnectionsPublicTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExchangeFinancialConnectionsPublicTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public_token"] = o.PublicToken
	return toSerialize, nil
}

func (o *ExchangeFinancialConnectionsPublicTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExchangeFinancialConnectionsPublicTokenRequest := _ExchangeFinancialConnectionsPublicTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExchangeFinancialConnectionsPublicTokenRequest)

	if err != nil {
		return err
	}

	*o = ExchangeFinancialConnectionsPublicTokenRequest(varExchangeFinancialConnectionsPublicTokenRequest)

	return err
}

type NullableExchangeFinancialConnectionsPublicTokenRequest struct {
	value *ExchangeFinancialConnectionsPublicTokenRequest
	isSet bool
}

func (v NullableExchangeFinancialConnectionsPublicTokenRequest) Get() *ExchangeFinancialConnectionsPublicTokenRequest {
	return v.value
}

func (v *NullableExchangeFinancialConnectionsPublicTokenRequest) Set(val *ExchangeFinancialConnectionsPublicTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExchangeFinancialConnectionsPublicTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExchangeFinancialConnectionsPublicTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchangeFinancialConnectionsPublicTokenRequest(val *ExchangeFinancialConnectionsPublicTokenRequest) *NullableExchangeFinancialConnectionsPublicTokenRequest {
	return &NullableExchangeFinancialConnectionsPublicTokenRequest{value: val, isSet: true}
}

func (v NullableExchangeFinancialConnectionsPublicTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchangeFinancialConnectionsPublicTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


