/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExchangeFinancialConnectionsPublicTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExchangeFinancialConnectionsPublicTokenResponse{}

// ExchangeFinancialConnectionsPublicTokenResponse struct for ExchangeFinancialConnectionsPublicTokenResponse
type ExchangeFinancialConnectionsPublicTokenResponse struct {
	// Token used for querying data on the user, ie account details, balances etc. This does NOT expire and should be stored securely.
	AccessToken string `json:"access_token"`
	// The id of the new financial connection. Every webhook will be sent with this id. Use this id when calling the GET /financial_connection/${financial_connection_id} endpoint. 
	FinancialConnectionId string `json:"financial_connection_id"`
	Institution *FinancialInstitution `json:"institution,omitempty"`
	Aggregator Aggregator `json:"aggregator"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId string `json:"request_id"`
}

type _ExchangeFinancialConnectionsPublicTokenResponse ExchangeFinancialConnectionsPublicTokenResponse

// NewExchangeFinancialConnectionsPublicTokenResponse instantiates a new ExchangeFinancialConnectionsPublicTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchangeFinancialConnectionsPublicTokenResponse(accessToken string, financialConnectionId string, aggregator Aggregator, requestId string) *ExchangeFinancialConnectionsPublicTokenResponse {
	this := ExchangeFinancialConnectionsPublicTokenResponse{}
	this.AccessToken = accessToken
	this.FinancialConnectionId = financialConnectionId
	this.Aggregator = aggregator
	this.RequestId = requestId
	return &this
}

// NewExchangeFinancialConnectionsPublicTokenResponseWithDefaults instantiates a new ExchangeFinancialConnectionsPublicTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchangeFinancialConnectionsPublicTokenResponseWithDefaults() *ExchangeFinancialConnectionsPublicTokenResponse {
	this := ExchangeFinancialConnectionsPublicTokenResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetFinancialConnectionId returns the FinancialConnectionId field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetFinancialConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FinancialConnectionId
}

// GetFinancialConnectionIdOk returns a tuple with the FinancialConnectionId field value
// and a boolean to check if the value has been set.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetFinancialConnectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinancialConnectionId, true
}

// SetFinancialConnectionId sets field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) SetFinancialConnectionId(v string) {
	o.FinancialConnectionId = v
}

// GetInstitution returns the Institution field value if set, zero value otherwise.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetInstitution() FinancialInstitution {
	if o == nil || IsNil(o.Institution) {
		var ret FinancialInstitution
		return ret
	}
	return *o.Institution
}

// GetInstitutionOk returns a tuple with the Institution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetInstitutionOk() (*FinancialInstitution, bool) {
	if o == nil || IsNil(o.Institution) {
		return nil, false
	}
	return o.Institution, true
}

// HasInstitution returns a boolean if a field has been set.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) HasInstitution() bool {
	if o != nil && !IsNil(o.Institution) {
		return true
	}

	return false
}

// SetInstitution gets a reference to the given FinancialInstitution and assigns it to the Institution field.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) SetInstitution(v FinancialInstitution) {
	o.Institution = &v
}

// GetAggregator returns the Aggregator field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetAggregator() Aggregator {
	if o == nil {
		var ret Aggregator
		return ret
	}

	return o.Aggregator
}

// GetAggregatorOk returns a tuple with the Aggregator field value
// and a boolean to check if the value has been set.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetAggregatorOk() (*Aggregator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregator, true
}

// SetAggregator sets field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) SetAggregator(v Aggregator) {
	o.Aggregator = v
}

// GetRequestId returns the RequestId field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ExchangeFinancialConnectionsPublicTokenResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ExchangeFinancialConnectionsPublicTokenResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o ExchangeFinancialConnectionsPublicTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExchangeFinancialConnectionsPublicTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["financial_connection_id"] = o.FinancialConnectionId
	if !IsNil(o.Institution) {
		toSerialize["institution"] = o.Institution
	}
	toSerialize["aggregator"] = o.Aggregator
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *ExchangeFinancialConnectionsPublicTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"financial_connection_id",
		"aggregator",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExchangeFinancialConnectionsPublicTokenResponse := _ExchangeFinancialConnectionsPublicTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExchangeFinancialConnectionsPublicTokenResponse)

	if err != nil {
		return err
	}

	*o = ExchangeFinancialConnectionsPublicTokenResponse(varExchangeFinancialConnectionsPublicTokenResponse)

	return err
}

type NullableExchangeFinancialConnectionsPublicTokenResponse struct {
	value *ExchangeFinancialConnectionsPublicTokenResponse
	isSet bool
}

func (v NullableExchangeFinancialConnectionsPublicTokenResponse) Get() *ExchangeFinancialConnectionsPublicTokenResponse {
	return v.value
}

func (v *NullableExchangeFinancialConnectionsPublicTokenResponse) Set(val *ExchangeFinancialConnectionsPublicTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExchangeFinancialConnectionsPublicTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExchangeFinancialConnectionsPublicTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchangeFinancialConnectionsPublicTokenResponse(val *ExchangeFinancialConnectionsPublicTokenResponse) *NullableExchangeFinancialConnectionsPublicTokenResponse {
	return &NullableExchangeFinancialConnectionsPublicTokenResponse{value: val, isSet: true}
}

func (v NullableExchangeFinancialConnectionsPublicTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchangeFinancialConnectionsPublicTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


