/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"fmt"
)

// CreateLinkTokenRequestTellerConfigAccountFilterCredit - struct for CreateLinkTokenRequestTellerConfigAccountFilterCredit
type CreateLinkTokenRequestTellerConfigAccountFilterCredit struct {
	CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf *CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf
	String *string
}

// CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOfAsCreateLinkTokenRequestTellerConfigAccountFilterCredit is a convenience function that returns CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf wrapped in CreateLinkTokenRequestTellerConfigAccountFilterCredit
func CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOfAsCreateLinkTokenRequestTellerConfigAccountFilterCredit(v *CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf) CreateLinkTokenRequestTellerConfigAccountFilterCredit {
	return CreateLinkTokenRequestTellerConfigAccountFilterCredit{
		CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf: v,
	}
}

// stringAsCreateLinkTokenRequestTellerConfigAccountFilterCredit is a convenience function that returns string wrapped in CreateLinkTokenRequestTellerConfigAccountFilterCredit
func StringAsCreateLinkTokenRequestTellerConfigAccountFilterCredit(v *string) CreateLinkTokenRequestTellerConfigAccountFilterCredit {
	return CreateLinkTokenRequestTellerConfigAccountFilterCredit{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateLinkTokenRequestTellerConfigAccountFilterCredit) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf)
	if err == nil {
		jsonCreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf, _ := json.Marshal(dst.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf)
		if string(jsonCreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf) == "{}" { // empty struct
			dst.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf = nil
		} else {
			match++
		}
	} else {
		dst.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateLinkTokenRequestTellerConfigAccountFilterCredit)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateLinkTokenRequestTellerConfigAccountFilterCredit)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateLinkTokenRequestTellerConfigAccountFilterCredit) MarshalJSON() ([]byte, error) {
	if src.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf != nil {
		return json.Marshal(&src.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateLinkTokenRequestTellerConfigAccountFilterCredit) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf != nil {
		return obj.CreateLinkTokenRequestTellerConfigAccountFilterCreditOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit struct {
	value *CreateLinkTokenRequestTellerConfigAccountFilterCredit
	isSet bool
}

func (v NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit) Get() *CreateLinkTokenRequestTellerConfigAccountFilterCredit {
	return v.value
}

func (v *NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit) Set(val *CreateLinkTokenRequestTellerConfigAccountFilterCredit) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkTokenRequestTellerConfigAccountFilterCredit(val *CreateLinkTokenRequestTellerConfigAccountFilterCredit) *NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit {
	return &NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit{value: val, isSet: true}
}

func (v NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkTokenRequestTellerConfigAccountFilterCredit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


