/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchFinancialInstitutionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchFinancialInstitutionsResponse{}

// SearchFinancialInstitutionsResponse struct for SearchFinancialInstitutionsResponse
type SearchFinancialInstitutionsResponse struct {
	FinancialInstitutions []FinancialInstitution `json:"financial_institutions"`
	// An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
	RequestId *string `json:"request_id,omitempty"`
}

type _SearchFinancialInstitutionsResponse SearchFinancialInstitutionsResponse

// NewSearchFinancialInstitutionsResponse instantiates a new SearchFinancialInstitutionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchFinancialInstitutionsResponse(financialInstitutions []FinancialInstitution) *SearchFinancialInstitutionsResponse {
	this := SearchFinancialInstitutionsResponse{}
	this.FinancialInstitutions = financialInstitutions
	return &this
}

// NewSearchFinancialInstitutionsResponseWithDefaults instantiates a new SearchFinancialInstitutionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchFinancialInstitutionsResponseWithDefaults() *SearchFinancialInstitutionsResponse {
	this := SearchFinancialInstitutionsResponse{}
	return &this
}

// GetFinancialInstitutions returns the FinancialInstitutions field value
func (o *SearchFinancialInstitutionsResponse) GetFinancialInstitutions() []FinancialInstitution {
	if o == nil {
		var ret []FinancialInstitution
		return ret
	}

	return o.FinancialInstitutions
}

// GetFinancialInstitutionsOk returns a tuple with the FinancialInstitutions field value
// and a boolean to check if the value has been set.
func (o *SearchFinancialInstitutionsResponse) GetFinancialInstitutionsOk() ([]FinancialInstitution, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinancialInstitutions, true
}

// SetFinancialInstitutions sets field value
func (o *SearchFinancialInstitutionsResponse) SetFinancialInstitutions(v []FinancialInstitution) {
	o.FinancialInstitutions = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *SearchFinancialInstitutionsResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFinancialInstitutionsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *SearchFinancialInstitutionsResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *SearchFinancialInstitutionsResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o SearchFinancialInstitutionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchFinancialInstitutionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["financial_institutions"] = o.FinancialInstitutions
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

func (o *SearchFinancialInstitutionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"financial_institutions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchFinancialInstitutionsResponse := _SearchFinancialInstitutionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchFinancialInstitutionsResponse)

	if err != nil {
		return err
	}

	*o = SearchFinancialInstitutionsResponse(varSearchFinancialInstitutionsResponse)

	return err
}

type NullableSearchFinancialInstitutionsResponse struct {
	value *SearchFinancialInstitutionsResponse
	isSet bool
}

func (v NullableSearchFinancialInstitutionsResponse) Get() *SearchFinancialInstitutionsResponse {
	return v.value
}

func (v *NullableSearchFinancialInstitutionsResponse) Set(val *SearchFinancialInstitutionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchFinancialInstitutionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchFinancialInstitutionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchFinancialInstitutionsResponse(val *SearchFinancialInstitutionsResponse) *NullableSearchFinancialInstitutionsResponse {
	return &NullableSearchFinancialInstitutionsResponse{value: val, isSet: true}
}

func (v NullableSearchFinancialInstitutionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchFinancialInstitutionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


