/*
Fuse

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fuse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SelectFinancialInstitutionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectFinancialInstitutionsRequest{}

// SelectFinancialInstitutionsRequest struct for SelectFinancialInstitutionsRequest
type SelectFinancialInstitutionsRequest struct {
	// The session client secret created.
	SessionClientSecret string `json:"session_client_secret"`
	// The selected financial institution id
	FinancialInstitutionId string `json:"financial_institution_id"`
}

type _SelectFinancialInstitutionsRequest SelectFinancialInstitutionsRequest

// NewSelectFinancialInstitutionsRequest instantiates a new SelectFinancialInstitutionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectFinancialInstitutionsRequest(sessionClientSecret string, financialInstitutionId string) *SelectFinancialInstitutionsRequest {
	this := SelectFinancialInstitutionsRequest{}
	this.SessionClientSecret = sessionClientSecret
	this.FinancialInstitutionId = financialInstitutionId
	return &this
}

// NewSelectFinancialInstitutionsRequestWithDefaults instantiates a new SelectFinancialInstitutionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectFinancialInstitutionsRequestWithDefaults() *SelectFinancialInstitutionsRequest {
	this := SelectFinancialInstitutionsRequest{}
	return &this
}

// GetSessionClientSecret returns the SessionClientSecret field value
func (o *SelectFinancialInstitutionsRequest) GetSessionClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionClientSecret
}

// GetSessionClientSecretOk returns a tuple with the SessionClientSecret field value
// and a boolean to check if the value has been set.
func (o *SelectFinancialInstitutionsRequest) GetSessionClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionClientSecret, true
}

// SetSessionClientSecret sets field value
func (o *SelectFinancialInstitutionsRequest) SetSessionClientSecret(v string) {
	o.SessionClientSecret = v
}

// GetFinancialInstitutionId returns the FinancialInstitutionId field value
func (o *SelectFinancialInstitutionsRequest) GetFinancialInstitutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FinancialInstitutionId
}

// GetFinancialInstitutionIdOk returns a tuple with the FinancialInstitutionId field value
// and a boolean to check if the value has been set.
func (o *SelectFinancialInstitutionsRequest) GetFinancialInstitutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinancialInstitutionId, true
}

// SetFinancialInstitutionId sets field value
func (o *SelectFinancialInstitutionsRequest) SetFinancialInstitutionId(v string) {
	o.FinancialInstitutionId = v
}

func (o SelectFinancialInstitutionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectFinancialInstitutionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_client_secret"] = o.SessionClientSecret
	toSerialize["financial_institution_id"] = o.FinancialInstitutionId
	return toSerialize, nil
}

func (o *SelectFinancialInstitutionsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_client_secret",
		"financial_institution_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSelectFinancialInstitutionsRequest := _SelectFinancialInstitutionsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSelectFinancialInstitutionsRequest)

	if err != nil {
		return err
	}

	*o = SelectFinancialInstitutionsRequest(varSelectFinancialInstitutionsRequest)

	return err
}

type NullableSelectFinancialInstitutionsRequest struct {
	value *SelectFinancialInstitutionsRequest
	isSet bool
}

func (v NullableSelectFinancialInstitutionsRequest) Get() *SelectFinancialInstitutionsRequest {
	return v.value
}

func (v *NullableSelectFinancialInstitutionsRequest) Set(val *SelectFinancialInstitutionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectFinancialInstitutionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectFinancialInstitutionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectFinancialInstitutionsRequest(val *SelectFinancialInstitutionsRequest) *NullableSelectFinancialInstitutionsRequest {
	return &NullableSelectFinancialInstitutionsRequest{value: val, isSet: true}
}

func (v NullableSelectFinancialInstitutionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectFinancialInstitutionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


